### ISSUE TITLE
`qubit_subset_finders.find_lines()` fails with asymmetric coupling maps

### ISSUE THREAD

**Issue by Durd3nT** [qiskit-community/qopt-best-practices#13]
### Environment

- **Qiskit version**: 0.45.1
- **Python version**: 3.10
- **Operating system**: Mac OS

### What is happening?

The paths returned by `rustworkx.all_pairs_all_simple_paths` depend on the directedness of the graph. The coupling maps auf new backends are all directed and thus need to be symmetrised for `rustworkx.all_pairs_all_simple_paths` to return all qubit lines of certain length, irrespective of the directedness of the coupling map.

### How can we reproduce the issue?

Pass a backend with directed coupling map to `qubit_subset_finders.find_lines()`.

### What should happen?

Should find all lines of length `num_qubits`.

### Any suggestions?

Call `CouplingMap.make_symmetric()` before calling `rustworkx.all_pairs_all_simple_paths`.

**Comment by ElePT** [comment]
Closed in https://github.com/qiskit-community/qopt-best-practices/pull/14
